name: Reusable Image Builder

on:
  workflow_call:
    inputs:
      dockerfile:
        required: true
        type: string
      image-tag:
        required: true
        type: string
      cache-tag:
        required: true
        type: string
      build-args:
        required: false
        default: ""
        type: string
      build-platforms:
        required: false
        default: linux/amd64,linux/arm64,linux/arm/v7
        type: string

jobs:
  build-image:
    name: Build ${{ inputs.dockerfile }}
    runs-on: ubuntu-22.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Build ${{ inputs.dockerfile }}
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ${{ inputs.dockerfile }}
          tags: ${{ inputs.image-tag }}
          platforms: ${{ inputs.build-platforms }}
          build-args: ${{ inputs.build-args }}
          push: true
          cache-from: ${{ inputs.cache-tag }}
          cache-to: ${{ inputs.cache-tag }}
